application: pajaspoint
version: 2
runtime: python
api_version: 1

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /update_friends
  script: main.py
  login: admin

- url: /update_new_pajas_point
  script: main.py
  login: admin

- url: .*
  script: main.py
